# Options for analysis running.
run:
  # Default concurrency is a available CPU number.
  concurrency: 4
  # Timeout for analysis, e.g. 30s, 5m.
  timeout: 1m
  # Exit code when at least one issue was found.
  issues-exit-code: 1
  # Include test files or not.
  tests: true

# Output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number
  # Print lines of code with issue.
  print-issued-lines: true
  # Print linter name in the end of issue text.
  print-linter-name: true

# All available settings of specific linters.
linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    check-type-assertions: true
  govet:
    # Report about shadowed variables.
    check-shadowing: true
  gocyclo:
    # Minimal code complexity to report.
    min-complexity: 10
  dupl:
    # Tokens count to trigger issue.
    threshold: 100
  goconst:
    # Minimal length of string constant.
    min-len: 3
    # Minimal occurrences count to trigger.
    min-occurrences: 3
  misspell:
    # Correct spellings using locale preferences for US or UK.
    locale: US

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gosec
    - gofmt
    - goimports
    - misspell
    - unconvert
    - goconst
    - unparam
  disable-all: false
  fast: false

issues:
  # Maximum issues count per one linter. Set to 0 to disable.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable.
  max-same-issues: 0

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

